### ISSUE TITLE
Changing exp rate/stages doesn't work

### ISSUE THREAD

**Issue by Silba93** [Black-Tek/BlackTek-Server#16]
In config.lua both rateExp and experienceStages don't have any effect on gained exp from monsters

Set any stages or rate you want in config, (can be confirmed in-game with !serverinfo command) and kill any monster, you will always get the base exp set in the monster xml file and not the multiplied rate

**Comment by Codinablack** [comment]
The known fix for this is that there is not a default onGainExperience event for players in lua, and to fix this bug you create one. 

This bug is also marked and will be fixed

**Comment by Codinablack** [comment]
718d9d39bc078d55a7968a1b7460473afa471b92 Resolves this.
