### ISSUE TITLE
"using" doors on a god character causes them to change incorrectly into other things/doors

### ISSUE THREAD

**Issue by Silba93** [Black-Tek/BlackTek-Server#17]
"use" a door on a god character and instead of opening/closing as normal, it is changed into other things or other doors/frames
doors seem to work fine on normal characters

https://github.com/user-attachments/assets/332ca81e-0e48-4110-9346-3246fa025203

**Comment by Codinablack** [comment]
The fix for this has already been found just not added yet. If anyone needs to fix on their own server without waiting, you just remove the access checks in the doors script.

**Comment by Codinablack** [comment]
7866942597cc79f8139eb30e1e01dfbc91906c34 Resolves this.
