### ISSUE TITLE
Decimal points being visible when undesired

### ISSUE THREAD

**Issue by Silba93** [Black-Tek/BlackTek-Server#18]
After switching to blacktek many of my scripts produce number values that end with a decimal point visible and it's very ugly. I'm unsure yet if it has any other effects than just being ugly. It's been discussed and apparently is due to the change from LuaJIT to Lua 5.4

It's also present in default scripts such as /clean.

![decimalpoints2](https://github.com/user-attachments/assets/0f437e69-8fe1-4a04-9893-b824af598b67)
![decimalpoints](https://github.com/user-attachments/assets/aa9298fb-2c49-498c-97b4-f86e75ddf724)

**Comment by Codinablack** [comment]
There is a known fix for this, the problem occurred from dropping luajit in favor of lua.

The fix for this is to swap usage of the luapushnumber and luapushinteger methods, this fix will be implemented for Black Tek eventually.

**Comment by Codinablack** [comment]
After the above three commits, safe to say this is fully resolved.
