### ISSUE TITLE
Imbuement Life/Mana Leech

### ISSUE THREAD

**Issue by creativess777** [Black-Tek/BlackTek-Server#36]
Issue: Incorrect Life/Mana Leech Recovery Values
Description
Life and Mana Leech imbuements recover only 1-3 HP/mana per hit across all tiers (Basic, Intricate, Powerful), making higher tiers ineffective.

Steps to Reproduce
Equip any tier of Life/Mana Leech imbuement.
Attack a target.
Observe recovery remains fixed at 1-3 HP/mana regardless of tier.
![TibiafunGL_MTPWmJ44NM](https://github.com/user-attachments/assets/0b9b4674-1a27-40bf-860e-89cee814d8d9)

**Comment by Codinablack** [comment]
Have you tried spending mana to give it room to gain more than 1 at a time? I don't think you should be getting any mana at all if you have full mana, but I can't remember for sure if I wrote such restrictions or not, but I think the game will probably not allow you to gain more than you are missing.

**Comment by Codinablack** [comment]
Confirmed not a bug in BlackTek Sources.
