### ISSUE TITLE
Exani hur / Exiva doesn't work

### ISSUE THREAD

**Issue by gojtan** [Black-Tek/BlackTek-Server#37]
As title 

Exani hur up/down parameters doesn't seem to work. Same with exiva.

Adding parameters (with or without "") makes it act like it isn't a spell.

**Comment by Codinablack** [comment]
Interesting. I believe someone told me this already and I had thought it was due to the change from luajit to lua, but I guess that isn't the case if you are using the most current version of the server, or at least a version that includes this fix 9076d84802316bcf23508f4a0293ff0826bfbc6a

Are you using latest sources, or at least a version that includes that commit?

**Comment by gojtan** [comment]
No, I am unfortunately using an earlier branch.
Could possible be fixed then, i'll try a newer version when Ive got time! Nice, good job!

**Comment by Codinablack** [comment]
> No, I am unfortunately using an earlier branch. Could possible be fixed then, i'll try a newer version when Ive got time! Nice, good job!

If you are running on windows right now, you can grab a newer version from our release section and just replace the executable for a quick test to see if it resolves the problem... if you are on linux, I will have binaries for them soon.

**Comment by gojtan** [comment]
![image](https://github.com/user-attachments/assets/245c211d-f799-4755-a697-798629723bb8)

![image](https://github.com/user-attachments/assets/314d7639-809b-48d1-8bca-f0b24e0352de)

Tried with latest precompiled .exe, still does not recognize exiva nor exani hur when adding parameters. Writing "Exani hur" without parameters poffs me with a "Sorry not possible"

**Comment by Codinablack** [comment]
> ![image](https://private-user-images.githubusercontent.com/62619077/399129932-245c211d-f799-4755-a697-798629723bb8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU0Mjk4MjQsIm5iZiI6MTczNTQyOTUyNCwicGF0aCI6Ii82MjYxOTA3Ny8zOTkxMjk5MzItMjQ1YzIxMWQtZjc5OS00NzU1LWE2OTctNzk4NjI5NzIzYmI4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI4VDIzNDUyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEyOWJmNTFmZmQ2NDhlZDczZWM1NzU5NjU5MDFkOTRlNzI3YjMxODQwZDQ0Y2VhOGY2YzZmYjdjMjkxZTI0MmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.z6kyBsyo8z5xgQ-i69J_391RgxICgcvs__WS5pLfNO8)
> 
> ![image](https://private-user-images.githubusercontent.com/62619077/399129958-314d7639-809b-48d1-8bca-f0b24e0352de.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU0Mjk4MjQsIm5iZiI6MTczNTQyOTUyNCwicGF0aCI6Ii82MjYxOTA3Ny8zOTkxMjk5NTgtMzE0ZDc2MzktODA5Yi00OGQxLThiY2EtZjBiMjRlMDM1MmRlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI4VDIzNDUyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc5YzIxMjk0MTdmZjhlNDVlOTg1NjgwZTdmMTRlNmIzMjVmYzZiNzViODhlNWIyMzU1ODhiODQ5NzE0M2NmYmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Jg1JUPNjUUM5JlWDJITWELuXmvV25RgIP9s3op4i15w)
> 
> Tried with latest precompiled .exe, still does not recognize exiva nor exani hur when adding parameters. Writing "Exani hur" without parameters poffs me with a "Sorry not possible"

Thanks for confirming! I have also had another confirm, and am currently digging into the matter
